version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    environment:
      # MONGO_INITDB_DATABASE: bd-killki
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      # MONGO_URI: mongodb://myuser:mypassword@127.0.0.1:27017/?authMechanism=DEFAULT
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  nestjs_app:
    build:
      context: ./
      dockerfile: Dockerfile  # Nombre del archivo Dockerfile para la aplicación NestJS
    container_name: nestjs_app_container
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"  # Ajusta el puerto según el puerto expuesto por tu aplicación NestJS

volumes:
  mongodb-data:
