version: "3.7"

services:
  db:
    image: mongo
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  mongodb-data:
